name: Tests

on:
  push:
    tags:
    branches:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Caching
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: go-${{ hashFiles('**/go.sum') }}
          restore-keys: go-

      - name: Dependencies
        run: go mod vendor

      - name: Checksum
        run: go mod verify

      - name: Test
        run: go test -short -v -failfast ./...
